linters:
  LineLength:
    max: 120
    
  RuboCop:
    enabled: true
    ignored_cops:
      - Layout/ArgumentAlignment
      - Layout/LineLength
      - Layout/TrailingEmptyLines
      
  ConsecutiveControlStatements:
    max_consecutive: 2
    
  RedundantDiv:
    enabled: true
    
  EmptyLines:
    enabled: true
    
  TrailingWhitespace:
    enabled: true

  TrailingBlankLines:
    enabled: false
