services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: book_track
      POSTGRES_DB: book_track_development
      POSTGRES_TEST_DB: book_track_test
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && bin/dev"
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle
    environment:
      - DATABASE_URL=postgres://book_track:password@db/book_track_development
      - RAILS_ENV=development
      - REDIS_URL=redis://redis:6379/1
      - BINDING=0.0.0.0
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
  bundle_cache:
