name: Renovate
on:
  schedule:
    - cron: '0 0 * * 1'  # Run every Monday at 00:00 UTC
  workflow_dispatch:      # Allow manual triggers

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v41.0.14
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          configurationFile: .github/renovate.json
